name: Update JSON from Google Sheets

on:
  schedule:
    - cron: "0 */3 * * *"  # alle 3 Stunden
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Sheets in JSON konvertieren
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1q3nkqzm67vOKxfeOX8hjaZaPBEzh2REI/gviz/tq?tqx=out:json" \
          | sed '1s/^[^(]*(//' | sed '$s/);$//' > ./data/hengste.json
          
          curl -L "https://docs.google.com/spreadsheets/d/1Q3Kh2XjiMoIfU_rTSZqLzCzHQ50hQuFS/gviz/tq?tqx=out:json" \
          | sed '1s/^[^(]*(//' | sed '$s/);$//' > ./data/stuten.json

      - name: Änderungen committen
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ./data/*.json
          git commit -m "Automatisches Update der JSON-Daten"
          git push
