name: Google Sheets to JSON

on:
  schedule:
    - cron: "0 * * * *"  # Läuft jede Stunde
  workflow_dispatch:      # Manuelles Starten möglich

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: Google Sheets zu JSON exportieren
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          SHEET_ID_STUTEN: ${{ secrets.SHEET_ID_STUTEN }}
          SHEET_ID_HENGSTE: ${{ secrets.SHEET_ID_HENGSTE }}
        run: node ./scripts/google-sheets-to-json.mjs

      - name: Änderungen prüfen und ggf. committen
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ./data/*.json

          # Nur committen, wenn Änderungen vorhanden sind
          if git diff --quiet; then
            echo "Keine Änderungen – kein Commit nötig."
          else
            git commit -m "Automatisches Update der JSON-Daten"
            git push
            echo "Änderungen wurden erfolgreich gepusht."
          fi
