name: Update JSON from Google Sheets

on:
  schedule:
    - cron: "0 * * * *"   # Läuft stündlich
  workflow_dispatch:       # Manuell auslösbar

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Wichtig für rebase

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pandas openpyxl requests

      - name: Download Stuten CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/<DEINE_STUTEN_ID>/export?format=csv" -o data/stuten.csv

      - name: Download Hengste CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/<DEINE_HENGSTE_ID>/export?format=csv" -o data/hengste.csv

      - name: Convert CSV to JSON
        run: |
          python - <<'EOF'
          import pandas as pd
          stuten = pd.read_csv("data/stuten.csv")
          hengste = pd.read_csv("data/hengste.csv")

          stuten.to_json("data/stuten.json", orient="records", force_ascii=False, indent=2)
          hengste.to_json("data/hengste.json", orient="records", force_ascii=False, indent=2)
          EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*.json
          git commit -m "Update JSON from Google Sheets" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
