name: Update JSON from Google Sheets

on:
  schedule:
    - cron: '0 */3 * * *' # alle 3 Stunden
  workflow_dispatch:       # manuell startbar

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run conversion script
        env:
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          HENGSTE_SHEET_ID: "1q3nkqzm67vOKxfeOX8hjaZaPBEzh2REI"
          STUTEN_SHEET_ID: "1Q3Kh2XjiMoIfU_rTSZqLzCzHQ50hQuFS"
        run: node scripts/convert-sheets-to-json.js

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push (safe update branch)
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git checkout -B update-json
          git add data/*.json
          git commit -m "🔄 Auto-update JSON from Google Sheets ($(date +'%Y-%m-%d %H:%M'))"
          git push origin update-json --force

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-json
          base: main
          title: "🔄 Auto-Update JSON from Google Sheets"
          body: "Automatisch generierte Aktualisierung der Daten aus Google Sheets."
