name: Update JSON from Google Sheets

on:
  schedule:
    - cron: "0 */3 * * *" # alle 3 Stunden
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Abhängigkeiten installieren
        run: npm install node-fetch@3

      - name: Google Sheets in JSON umwandeln
        run: node scripts/convert-sheets-to-json.js

      - name: Änderungen committen und pushen
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/*.json
          git commit -m "Update JSON from Google Sheets" || echo "Keine Änderungen"
          git push
